version: 0.2

phases:
  install:
    commands:
      - echo Installing build dependencies
  build:
    commands:
      - echo Build started on `date`
      - echo Packaging static website files
artifacts:
  files:
    - '**/*'
  base-directory: app
